baseURL = "https://blog.simonrw.com"
locale = "en-us"
title = "Circularspace"
theme = ["hugo-admonitions", "anubis"]

[params]
style = "auto"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[build.environment]
HUGO_VERSION = "0.109.0"

[menu]

  [[menu.main]]
  identifier = "archive"
  name = "Archive"
  title = "Archive"
  url = "/posts/"
  weight = 0.0
